openapi: 3.0.3
info:
  title: next-catalog-service-api
  description: 'Next Catalog Service API (CATAS)'
  contact:
    email: backend@sii.com
  version: "0.5"

servers:
  - url: http://tbd

tags:
  - name: next-catalog-data
    description: Next catalog data

paths:

  /catalog/{carlineId}/modelId}:
    get:
      tags:
        - next-catalog-data
      summary: List all equipments by model id.
      description: Return the entire catalog for a model.
      operationId: getCatalogDataForModel
      parameters:
        - $ref: "#/components/parameters/carlineIdPathParameter"
        - $ref: "#/components/parameters/modelIdParameter"
      responses:
        '200':
          description: Returning a list of exterior
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogResponse"
          headers:
            X-DataVersion:
              schema:
                type: string
              description: Data version
              example: "mv-3131"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"

components:

  schemas:


    CatalogResponse:
      type: object
      properties:
        carlineId:
          type: string
          example: "a1sb"
        groups:
          type: array
          items:
            $ref: "#/components/schemas/EquipmentGroup"
        extColors:
          type: array
          items:
            $ref: "#/components/schemas/ExteriorColor"
        interiorTiles:
          type: array
          items:
            $ref: "#/components/schemas/InteriorTiles"
        specialGroups:
          type: array
          items:
            $ref: "#/components/schemas/EquipmentGroup"
        bodyColors:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"
        roofColors:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"
        stealthItems:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"
        accesories:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"


    EquipmentGroup:
      type: object
      properties:
        id:
          type: string
          example: "infotainment"
        name:
          type: string
          example: "Infotainment/Technology"
          description: Name of the mbv lasche
        equipmentFamilies:
          type: array
          items:
            $ref: "#/components/schemas/EquipmentFamily"

    ExteriorColor:
      type: object
      properties:
        id:
          type: string
          example: "color-type:uni"
        familyName:
          type: string
          example: "Uni-Lacke"
        equipmentList:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"

    InteriorTiles:
      type: object
      properties:
        id:
          type: string
          example: "color-type:uni"
        familyName:
          type: string
          example: "Uni-Lacke"
        equipmentList:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"

    Accessories:
      type: object
      properties:
        id:
          type: string
          example: "color-type:uni"
        families:
          type: array
          items:
            $ref: "#/components/schemas/EquipmentFamily"

    EquipmentFamily:
      type: object
      properties:
        id:
          type: string
          example: "exterior.exterior"
        name:
          type: string
          example: "Exterior"
        equipments:
          type: array
          items:
            $ref: "#/components/schemas/Equipment"
    Equipment:
      type: object
      properties:
        id:
          type: string
          description: The eva key. Display id
          example: "C2D"
        mbvId:
          type: string
          description: The mbv id. Internal id
          example: "MRADC2D"
        renderCode:
          type: string
          description: The render code.
          example: "MRADC2D"
        name:
          type: string
          description: The name
          example: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
        equipmentType:
          $ref: "#/components/schemas/EquipmentType"
        isVisible:
          type: boolean
          description: The okapi is visible flag. Not used in nemo but in newDcc
          example: true
        marginable:
          type: boolean
          description: Not used in nemo but in newDcc
        price:
          type: number
          description: The mbv list price. Standards never have prices
          example: 0.00
        texts:
          type: array
          items:
            $ref: "#/components/schemas/Texts"
        media:
          type: array
          items:
            $ref: "#/components/schemas/Media"
        attributes:
          $ref: "#/components/schemas/AttributeInfo"
        content:
          type: array
          items:
            $ref: "#/components/schemas/PackageContent"
          description: |
            The content of the package.
      required:
        - name
        - equipmentType
        - id

    EquipmentType:
      type: string
      enum:
        - exterior
        - interior
        - standard
        - option
      example: option

    PackageContent:
      type: object
      properties:
        name:
          type: string
          description: name
          example: "tbd"
        id:
          type: string
          description: The id
          example: "tbd"
        mbvId:
          type: string
          description: the mbv id
          example: tbd
        evaKey:
          type: string
          example: "KK1"
      required:
        - name
        - id
        - mbvId

    Texts:
      type: object
      additionalProperties:
        type: string
        example:
          "ak_headline": "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          "ak_remarks": "<p><b>Hinweis</b>: Serie A1 Sportback S line 25 TFSI und 30 TFSI; A1 Sportback 35 TFSI</p>"
          "importname": "Räder, 10-Speichen, 6,5Jx16, Reifen modellspezifisch"
          "tyre-label-0": "https://eprel.ec.europa.eu/api/products/tyres/380866/labels?noRedirect=false&format=SVG&supplier_label=false"
          "tyre-pdf-0": "https://eprel.ec.europa.eu/api/products/tyres/380866/fiches?noRedirect=false&language=DE"
          "tyre-label-1": "https://eprel.ec.europa.eu/api/products/tyres/531164/labels?noRedirect=false&format=SVG&supplier_label=false"
          "tyre-pdf-1": "https://eprel.ec.europa.eu/api/products/tyres/531164/fiches?noRedirect=false&language=DE"

    Media:
      type: object
      additionalProperties:
        type: string
        example:
          "type": "wheel_image_small"
          "url": "//pre-mediaservice.audi.com/media/cdb/data/c27c5d15-2f86-4b22-aa2c-a6c1d038eac8.jpg"
          "mimeType": "image/jpeg"
          "width": 200
          "height": 200


    AttributeInfo:
      type: object
      additionalProperties:
        type: string
        example:
        # "Audi-Sport": "false"
        #  "tyre-season": "summer"
        #  "wheel-material": "light-metal"
        # "wheel-type": "default"
        # "wheel-size": "16"
        # "type": "wheel"*


    ModelFilter:
      type: object
      additionalProperties:
        type: string
      example:
        "Antrieb": "-"
        "Getriebeart": "S"
        "Motorart": "0"



    # Schema for error response body
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message




  parameters:
    carlineIdPathParameter:
      name: carlineId
      in: path
      required: true
      schema:
        type: string
        example: "a4limo"
        description: The id of the carline

    modelIdParameter:
      in: query
      name: modelId
      required: true
      schema:
        type: string
        example: "8vfanc-0-2020"
        description: The id of the model

  responses:

    NotFound:       # Can be referenced as '#/components/responses/NotFound'
      description: The specified resource was not found.

    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string

    GenericError:      # Can be referenced as '#/components/responses/GenericError'
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      name: X-API-KEY  # name of the header, query parameter or cookie
      in: header

